1
Genetiro/BackendOne pull request #10
Opened 2023-01-03 19:04 UTC by Genetiro

2023-01-05 12:05 UTC, Gusyatnikova requested changes

2023-01-05 12:05 UTC, Gusyatnikova commented on bild/docker-compose.yaml
> +      - db
В секции depends_on нужно указывать имя сервиса, в данном случае ваш сервис с бд называется sqlite3 - его и нужно указать вместо db. Мануал по docker-compose [вот](https://docs.docker.com/compose/compose-file/#depends_on)

2023-01-05 12:05 UTC, Gusyatnikova commented on bild/Dockerfile
> +ADD go.mod go.sum /m/
Вы хотите добавить в image файлы, которых нет в контесте билда. Dockerfile живет у вас в директории /build, а go.mod и go.sum - в корне проекта. Вы можете или указать директорию откуда брать эти файлы, либо унести Dockerfile в корень проекта.

2023-01-05 12:05 UTC, Gusyatnikova commented on bild/Dockerfile
> +RUN cd /m && go mod download
Неочевидное лично для меня название директории "m" - что оно значит, какие там будут размещены файлы?

2023-01-05 12:05 UTC, Gusyatnikova commented on bild/Dockerfile
> +COPY --from=modules /go/pkg /go/pkg
Разделять сборку на stages - это хорошо, но в данном проекте кажется излишним усложнением. Все что вам нужно - добавить в image проект целиком, загрузить зависимости и собрать на базе golang.

2023-01-05 12:05 UTC, Gusyatnikova commented on bild/Dockerfile
> +FROM scratch
Разделяйте этапы сборки пустыми строками - так ваш файл станет более читабельным

2023-01-05 12:05 UTC, Gusyatnikova commented on bild/Dockerfile
> +COPY --from=builder /etc/ssl/cert /etc/ssl/cert
О каких сертификатах идет речь? Они имеют место быть, но повторюсь, не усложняйте проект - сертификаты можно пока не использовать. Почитайте про принцип [KISS](https://en.wikipedia.org/wiki/KISS_principle)

2023-01-05 12:05 UTC, Gusyatnikova commented on cmd/main.go
> +	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
Создайте отдельный хендлер, как в LinkResources.Routes(). Общее правило - main должен быть как можно более коротким - обычно это всего несколько строк.

> func main() {
> service := app.NewService(context.Background())
> service.Run()
> service.ListenForShutdown()
> }

2023-01-05 12:05 UTC, Gusyatnikova commented on internal/transport/handlers.go
> +// @Param  input body ListLink true
> go init создает документы но с ошибкой: ParseComment error in file BackendOne\internal\transport\handlers.go :missing required param comment parameters "input body ListLink true" 

Вы видите эту ошибку, т.к. тип ListLink не определен. Если у тела, которое вы собираетесь принимать в методе  Delete, нет определенного типа, может быть это []string, например? 

> // @Param       input body      []string true "..."

2023-01-05 12:05 UTC, Gusyatnikova commented on cmd/main.go
> +	r.Get("/swagger/*", httpSwagger.Handler(
Вместо этого хендлера можно использовать `r.Get("/swagger/*", httpSwagger.WrapHandler)`

2023-01-05 12:05 UTC, Gusyatnikova commented on cmd/main.go
> +	httpSwagger "github.com/swaggo/http-swagger"
Также нужно импортировать сгенерированную командой swag init документацию, т.к. сваггер живет там `_ "github.com/Genetiro/BackendOne/docs"`

2023-01-05 12:05 UTC, Gusyatnikova commented on internal/server/server.go
> +	cancel()
Лучше использовать `defer cancel()` сразу после его объявления

2023-01-05 12:05 UTC, Gusyatnikova commented on internal/transport/handlers.go
> +
Нужно добавить описание возвращаемых http кодов для хендлеров

2023-01-05 12:05 UTC, Gusyatnikova commented on internal/transport/handlers.go
> +	db, err := sql.Open("sqlite3", "links.db")
Открытие коннекта к базе дублируется в каждом хендлере. Помимо сложностей в поддержке и дублирования кода это также замедляет работу программы. Вынесите эту сущность в отдельный пакет и переиспользуйте. Инициализируйте коннект к базе только 1 раз при старте программы.

2023-01-05 12:05 UTC, Gusyatnikova commented on internal/transport/shortner.go
> +	b := make([]byte, 5)
У вас формируется строка из 52 символов длиной 5, значит максимальное количество уникальных строк, которые можно получить: 52\*51\*50\*49\*48 ([Число размещений ](https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B7%D0%BC%D0%B5%D1%89%D0%B5%D0%BD%D0%B8%D0%B5)из n по k). Это ограничение, которое просто нужно иметь ввиду - например, освобождать неиспользуемые сокращения, или увеличить возможные комбинации, или ничего не делать - для текущего проекта такого предела точно хватит. Но вы должны понимать, что такое ограничение есть.

2023-01-05 12:05 UTC, Gusyatnikova commented on internal/transport/shortner.go
> +package transport
Сам механизм сокращения ссылок - это логика вашего приложения, она должна находится в своем отдельном пакете, т.к. никак не связана с транспортом. Например, вы можете добавить возможность просто вводить ссылки в консоль и получать в ответ сокращенные: механизм сокращения останется тем же, но пакет передачи данных будет уже не нужен.

2023-01-05 12:07 UTC, Gusyatnikova requested changes
В целом прогресс хороший, важно пофиксить docker-compose, swagger и аккуратно разделить функциональность по пакетам.

2023-01-08 09:55 UTC, Gusyatnikova reviewed
Виден прогресс, отлично. Критичные замечания это исправить роутинг, чтобы была возможность получить все сокращенные ссылки, сваггер поправить по примеру метода Delete и тесты переименовать.

2023-01-08 09:55 UTC, Gusyatnikova commented on internal/transport/handlers.go
> +		r.Get("/", rs.Get)       // GET /links/{short}
При таком роутинге мы не попадаем на //GET /links, т.к. если пойти на ссылку `http://localhost:8080/links/` , то попадем в путь `"/{short}"` как наиболее точный. Лучше короткую ссылку получать как обязательный query параметр.

2023-01-08 09:55 UTC, Gusyatnikova commented on internal/transport/handlers.go
> +	rows, err := dbase.Query("SELECT * FROM links.linkshort")
Вся работа с базой должна выполняться в отдельном пакете. Инкапсулируйте этот вызов в функцию: rs.dbHandler.GetShortLinks()

2023-01-08 09:55 UTC, Gusyatnikova commented on internal/transport/handlers_test.go
> +func CreateTest(t *testing.T) {
Сигнатура тестов в Го строго определена [тут](https://pkg.go.dev/testing). Должнобыть TestCreate

2023-01-08 09:55 UTC, Gusyatnikova commented on internal/transport/handlers.go
> +	tmpl, _ := template.ParseFiles("html/home.html")
Игнорирование ошибки почти всегда приводит к проблемам. Из-за этого тест Create падает. Здесь tmpl - nil, а потом в строке 95 вы пытаетесь вызвать метод у nil объекта и получаете `invalid memory address or nil pointer dereference`

2023-01-08 09:55 UTC, Gusyatnikova commented on internal/transport/handlers.go
> +func (rs LinkResources) Delete(w http.ResponseWriter, r *http.Request) {
Это единственный метод, который корректно отображается в сваггере. Возьмите его как пример и приведите остальные описания методов к такому же виду.

2023-01-08 09:55 UTC, Gusyatnikova commented on internal/transport/handlers_test.go
> +func ListTest(t *testing.T) {
Аналогично - требуется переименовать.

2023-01-08 09:55 UTC, Gusyatnikova commented on internal/transport/handlers.go
> +	tmpl, _ := template.ParseFiles("html/list.html")
Проверьте путь к html файлам. Для того, чтобы увидеть директорию html из директории transport нужно сначала перейти(../) в internal: transport->internal->html->list.html

2023-01-10 18:28 UTC, Genetiro commented
Заработал swagger)).  Перенес работу с базой данных в пакет database. Работу написал через методы, по этому приходятся в каждом хэндлере открывать базу данных и передавать ее в метод, но другого решения я пока не нашел. Тест функции List не проходит, выдает: no such table: links.linkshort; panic: runtime error: invalid memory address or nil pointer dereference. Я пробовал менять название таблицы в функции, но ошибка та же: no such table. И docker-compose никак не заработает, проблемы со сборкой контейнера shortner. Гугл по ошибке говорит о правах доступа(других вариантов не нашел), но у меня windows, chmod попробовать не смог, как и разные запуски от администратора, но может я не понимаю ошибку.

2023-01-10 18:30 UTC, Genetiro commented
Скрины ошибок приложил на портале gb

2023-01-10 19:34 UTC, Gusyatnikova reviewed
Хорошая работа, доводите проект до рабочего состояния и делайте merge этого ПР

2023-01-10 19:34 UTC, Gusyatnikova commented on internal/transport/handlers.go
> +type LinkResources struct{}
Добавьте в структуру LinkResources поле `repo *database.Db
`

2023-01-10 19:34 UTC, Gusyatnikova commented on internal/transport/handlers.go
> +	base, err := database.NewDB("./links.db")
Не нужно этого делать - у вас будет доступ к базе через поле в LinkResources

2023-01-10 19:34 UTC, Gusyatnikova commented on internal/transport/handlers.go
> +	list, _ := base.GetShortLinks()
1. `list, _ := rs.repo.GetShortLinks()`
2. Ошибку от бд обязательно нужно обрабатывать

2023-01-10 19:34 UTC, Gusyatnikova commented on internal/database/dbCon.go
> +}
Добавьте публичный метод `func (dbase *Db) Close()`, который будет закрывать соединение к базе

2023-01-10 19:34 UTC, Gusyatnikova commented on internal/database/dbCon.go
> +func DbCon() error {
Этот метод нужно удалить. Доступ должен быть по такой схеме: Создаете хендлер бд через функцию NewDB, передаете ее в структуру LinksResourses при ее создании, в хендлерах обращаетесь к полю LinksResourses

2023-01-10 19:34 UTC, Gusyatnikova commented on cmd/main.go
> +
```
linksRepo,err  := database.NewDb()
lr := transport.LinkResources{repo: linksRepo}

r.Mount("/links", lr.Routes())
```

2023-01-15 09:50 UTC, Genetiro commented
Прошли тесты, была ошибка в файле docker-compose.yaml. Запустились контейнеры. Но все еще не работают запросы по ссылке localhost:8080/links.

2023-01-15 09:55 UTC, merged